### ISSUE TITLE
Allow linking with any FSF/OSI approved license

### ISSUE THREAD

**Issue by clopez** [copyleft-next/copyleft-next#15] opened 2012-09-01 17:06 UTC
Hi,

IMHO one of the worst problems of the GPL is that it don't allows linking (static or dynamic) programs licensed under the GPL with some of the FSF/OSI approved licenses (OpenSSL,CDDL,PHP License...)

I think it will be a good idea to add an exception to this license that allows linking the software with ANY of the licenses considered as free software license by the FSF/OSI while at the same time forbids to link the software with any proprietary license.

Perhaps something like:

`In addition, as a special exception, the copyright holders give
permission to link the code of portions of this program with any
software licensed under a license that satisfies either the Free
Software Definition, version 1.111, as published by the Free Software
Foundation ("FSF") or the Open Source Definition, as published by
the Open Source Initiative, and distribute linked combinations
including the two.`

**Comment by richardfontana** [comment] 2012-09-02 00:30
Thanks for reporting this issue. I'm going to post it to the copyleft-next mailing list.

**Comment by ghost** [comment] 2012-12-30 18:01
> IMHO one of the worst problems of the GPL is that it don't allows linking (static or dynamic) programs licensed under the GPL with some of the FSF/OSI approved licenses (OpenSSL,CDDL,PHP License...)

FWIW, I will express support for this statement, and proposal.

Apart from ideological or other wishes developers may have, IMHO in too many cases, far too many cases, free development on the basis of existing Open Source code (libraries, applications, not-invented-here awesome bit) is blocked by license incompatibilities. They mean exactly: "you can't use x with y, even if they're both FOSS, because x is GPL and y is MPL 1.1".
This proposal, the way I see it, means basically: nothing in the license of x and y changes, they have the same requirements and they're used (built upon) in FOSS software, but they _can be used together_".
(of course, sometimes that means "nothing else changes except for this bit" :) )

Note: I admit I have taken intently MPL 1.1 as example, because it doesn't have any incompatibility issues from its side (afaik). The incompatibility comes from GPL side.

Note 2: IMHO the practical difference is very significant, between not being able to _use together_ two FOSS licensed code libraries (applications, etc), _and_ not being able to relicense one as another license ("distribute under"). Which seems to me (IANAL) the crux of the issue of "incompatibility".
Ability to use together means to build upon copylefted software in a sense, yes, but only for Open Source licensed software, so it doesn't affect in any other way its copyleft...

**Comment by richardfontana** [comment] 2013-04-24 03:19
Something like this proposal is implemented in https://github.com/richardfontana/copyleft-next/commit/b876a385f6beb93f0d9a094fee63e214afd8de3a
which allows for inbound compatibility for all licenses that are both FSF-free and OSI 'Open Source', other than GPLv2/GPLv3/AGPLv3. Closing.

**Closed as completed by richardfontana** 2013-04-24 03:19 UTC

**Comment by clopez** [comment] 2013-04-24 04:38
`An "Inbound Compatible License" is a license that is both approved
by the Open Source Initiative and classified as 'free' by the Free Software Foundation
as of the release date of this License`

I understand that the "as of the release date of this License" will break compatibility with future licenses that may be created after copyleft-next is released.

Think about it in terms of GPLv4 or CDDLv2. I suggest changing the sentence to be someting like:

`An "Inbound Compatible License" is a license that is both approved
by the Open Source Initiative and classified as 'free' by the Free Software Foundation
as of the release date of this License or (at your option) the date of today`

**Comment by richardfontana** [comment] 2013-04-24 13:32
Thanks, I see some benefits to this suggestion (essentially the issue is how problematic is it to lock down the set of compatible licenses to a particular degree). I won't reopen the issue here since I committed to cease using the GitHub issues tracker but I will keep this open in an informal sense (or in an formal sense once I get around to some other issue tracking solution).
